name: Lint

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Generate schemas and types
        run: npm run generate
      -
        name: Lint Source Code
        run: npm run lint
      -
        name: Lint Markdown
        run: |
          npm run doctoc
          git diff --exit-code
      -
        name: Lint Versions
        run: npx @coralproject/package-version-lint